name: Sublime Text Package Reviewer
description: GitHub Action for reviewing package control channel changes

inputs:
  base-sha:
    description: The SHA of the base commit to diff against
    required: true
  current-sha:
    description: The SHA of the current commit to diff against
    required: true

runs:
  using: 'composite'
  steps:
    - name: Review package
      shell: bash
      run: |
        python3 ${{ github.action_path }}/run-review-bot.py \
        --base-sha ${{ inputs.base-sha }} \
        --current-sha ${{ inputs.current-sha }} \
